// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise } from '../core/http.js';
import type { Account, RotateChallengeTokenResponse, RotateWebhookEventsHmacSecretResponse } from '../types.js';

export class Accounts {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Retrieves the current account for the token accessing the API
   * 
   * @example
   * ```ts
   * const account = await client.accounts.retrieve();
   * ```
   */
  retrieve(options?: RequestOptions): APIPromise<Account> {
    return this._client.requestAPI<Account>(() => {
      return { method: 'GET', path: `/v1/account` };
    }, options);
  }

  /**
   * Rotates the challenge token for the account
   * 
   * @example
   * ```ts
   * const rotateChallengeTokenResponse = await client.accounts.rotateChallengeToken();
   * ```
   */
  rotateChallengeToken(options?: RequestOptions): APIPromise<RotateChallengeTokenResponse> {
    return this._client.requestAPI<RotateChallengeTokenResponse>(() => {
      return { method: 'POST', path: `/v1/account:rotateChallengeToken` };
    }, options);
  }

  /**
   * Rotates the webhook signing key for the account
   * 
   * @example
   * ```ts
   * const rotateWebhookEventsHmacSecretResponse = await client.accounts.rotateWebhookSigningKey();
   * ```
   */
  rotateWebhookSigningKey(options?: RequestOptions): APIPromise<RotateWebhookEventsHmacSecretResponse> {
    return this._client.requestAPI<RotateWebhookEventsHmacSecretResponse>(() => {
      return { method: 'POST', path: `/v1/account:rotateWebhookSigningKey` };
    }, options);
  }
}
