// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateResourceMetadata, ListMemoryEntriesResponse, MemoryEntry, MemoryEntryCreateSpec, MemoryEntryDetail, MemoryEntryUpdateSpec, UpdateResourceMetadata } from '../types.js';

export interface MemoryEntryListParams {
  /**
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * Filter by key prefix (e.g., "skills/postmortem/" to list all entries
   *  under that hierarchy). Matches against the entry's key, not its name.
   */
  prefix?: string;
  /**
   * Free-form search query
   */
  query?: string;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
  /**
   * Sort order for results (asc or desc by creation time)
   */
  sortOrder?: string;
  /**
   * When set to true you may use more of your alloted API rate-limit
   */
  includeInfo?: boolean;
}

export interface MemoryEntryCreateParams {
  metadata: CreateResourceMetadata;
  spec: MemoryEntryCreateSpec;
  /**
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface MemoryEntryRetrieveParams {
  /**
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface MemoryEntryDeleteParams {
  /**
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface MemoryEntryUpdateParams {
  /**
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: UpdateResourceMetadata;
  spec?: MemoryEntryUpdateSpec;
  updateMask?: string;
}

export class MemoryEntries {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List memory entries
   * 
   * @example
   * ```ts
   * const page = await client.memoryLayers.entries.list('memory_layer_123');
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(memoryLayerId: string, params?: MemoryEntryListParams, options?: RequestOptions): Promise<Page<MemoryEntry>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListMemoryEntriesResponse>({ method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/memory_layers/${pathSegment('memoryLayerId', memoryLayerId)}/entries`, query: { limit: params?.limit, cursor: params?.cursor, prefix: params?.prefix, query: params?.query, labels: params?.labels, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list(memoryLayerId, { ..._base, cursor: cursor }, options));
  }

  /**
   * Create a new memory entry
   * 
   * @example
   * ```ts
   * const memoryEntryDetail = await client.memoryLayers.entries.create('memory_layer_123', { metadata: { name: 'sample' }, spec: { content: 'sample', key: 'sample', type: 'content' } });
   * ```
   */
  create(memoryLayerId: string, params: MemoryEntryCreateParams, options?: RequestOptions): APIPromise<MemoryEntryDetail> {
    return this._client.requestAPI<MemoryEntryDetail>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/memory_layers/${pathSegment('memoryLayerId', memoryLayerId)}/entries`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get a memory entry by ID
   * 
   * @example
   * ```ts
   * const memoryEntryDetail = await client.memoryLayers.entries.retrieve('memory_layer_123', '_123');
   * ```
   */
  retrieve(memoryLayerId: string, id: string, params?: MemoryEntryRetrieveParams, options?: RequestOptions): APIPromise<MemoryEntryDetail> {
    return this._client.requestAPI<MemoryEntryDetail>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/memory_layers/${pathSegment('memoryLayerId', memoryLayerId)}/entries/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * Delete a memory entry
   * 
   * @example
   * ```ts
   * await client.memoryLayers.entries.delete('memory_layer_123', '_123');
   * ```
   */
  delete(memoryLayerId: string, id: string, params?: MemoryEntryDeleteParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/memory_layers/${pathSegment('memoryLayerId', memoryLayerId)}/entries/${pathSegment('id', id)}`, void: true };
    }, options);
  }

  /**
   * Update a memory entry
   * 
   * @example
   * ```ts
   * const memoryEntryDetail = await client.memoryLayers.entries.update('memory_layer_123', '_123');
   * ```
   */
  update(memoryLayerId: string, id: string, params?: MemoryEntryUpdateParams, options?: RequestOptions): APIPromise<MemoryEntryDetail> {
    return this._client.requestAPI<MemoryEntryDetail>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'PATCH', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/memory_layers/${pathSegment('memoryLayerId', memoryLayerId)}/entries/${pathSegment('id', id)}`, body: { metadata: params?.metadata, spec: params?.spec, updateMask: params?.updateMask } };
    }, options);
  }
}
