// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise } from '../core/http.js';
import type { WhoamiResponse } from '../types.js';

export class Profiles {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Retrieves the profile for the credentials accessing the API
   * 
   * @example
   * ```ts
   * const whoamiResponse = await client.profiles.whoami();
   * ```
   */
  whoami(options?: RequestOptions): APIPromise<WhoamiResponse> {
    return this._client.requestAPI<WhoamiResponse>(() => {
      return { method: 'GET', path: `/v1/whoami` };
    }, options);
  }
}
