// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateResourceMetadata, ListToolSetSecretsResponse, ToolSetSecret, ToolSetSecretSpec, UpdateResourceMetadata } from '../types.js';

export interface ToolSetSecretListParams {
  /**
   * The workspace that owns the tool set.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * Filter expression (query param: prefix)
   */
  prefix?: string;
  /**
   * Free-form search query
   */
  query?: string;
  /**
   * Sort order for results (asc or desc by creation time)
   */
  sortOrder?: string;
  /**
   * When set to true you may use more of your alloted API rate-limit
   */
  includeInfo?: boolean;
}

export interface ToolSetSecretCreateParams {
  metadata: CreateResourceMetadata;
  spec: ToolSetSecretSpec;
  /**
   * The workspace that owns the tool set.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface ToolSetSecretRetrieveParams {
  /**
   * The workspace that owns the tool set.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface ToolSetSecretDeleteParams {
  /**
   * The workspace that owns the tool set.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface ToolSetSecretUpdateParams {
  /**
   * The workspace that owns the tool set.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: UpdateResourceMetadata;
  spec?: ToolSetSecretSpec;
  /**
   * Fields to update.
   */
  updateMask?: string;
}

export class ToolSetSecrets {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List tool set secrets
   * 
   * @example
   * ```ts
   * const page = await client.toolSets.secrets.list('tool_set_123');
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(toolSetId: string, params?: ToolSetSecretListParams, options?: RequestOptions): Promise<Page<ToolSetSecret>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListToolSetSecretsResponse>({ method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/tool_sets/${pathSegment('toolSetId', toolSetId)}/secrets`, query: { limit: params?.limit, cursor: params?.cursor, prefix: params?.prefix, query: params?.query, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list(toolSetId, { ..._base, cursor: cursor }, options));
  }

  /**
   * Create a new tool set secret
   * 
   * @example
   * ```ts
   * const toolSetSecret = await client.toolSets.secrets.create('tool_set_123', { metadata: { name: 'sample' }, spec: {  } });
   * ```
   */
  create(toolSetId: string, params: ToolSetSecretCreateParams, options?: RequestOptions): APIPromise<ToolSetSecret> {
    return this._client.requestAPI<ToolSetSecret>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/tool_sets/${pathSegment('toolSetId', toolSetId)}/secrets`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get a tool set secret by ID
   * 
   * @example
   * ```ts
   * const toolSetSecret = await client.toolSets.secrets.retrieve('tool_set_123', '_123');
   * ```
   */
  retrieve(toolSetId: string, id: string, params?: ToolSetSecretRetrieveParams, options?: RequestOptions): APIPromise<ToolSetSecret> {
    return this._client.requestAPI<ToolSetSecret>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/tool_sets/${pathSegment('toolSetId', toolSetId)}/secrets/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * Delete a tool set secret
   * 
   * @example
   * ```ts
   * await client.toolSets.secrets.delete('tool_set_123', '_123');
   * ```
   */
  delete(toolSetId: string, id: string, params?: ToolSetSecretDeleteParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/tool_sets/${pathSegment('toolSetId', toolSetId)}/secrets/${pathSegment('id', id)}`, void: true };
    }, options);
  }

  /**
   * Update a tool set secret
   * 
   * @example
   * ```ts
   * const toolSetSecret = await client.toolSets.secrets.update('tool_set_123', '_123');
   * ```
   */
  update(toolSetId: string, id: string, params?: ToolSetSecretUpdateParams, options?: RequestOptions): APIPromise<ToolSetSecret> {
    return this._client.requestAPI<ToolSetSecret>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'PATCH', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/tool_sets/${pathSegment('toolSetId', toolSetId)}/secrets/${pathSegment('id', id)}`, body: { metadata: params?.metadata, spec: params?.spec, updateMask: params?.updateMask } };
    }, options);
  }
}
