// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment } from '../core/http.js';
import type { SearchToolsOrToolSetsResponse } from '../types.js';

export interface ToolSearchSearchOrSetsParams {
  query: string;
  /**
   * NOTE: `query` is runtime-required (buf.validate min_len), but gnostic
   *  does not propagate message-level schema `required` to GET query
   *  parameters — overlay.yaml marks the parameter required instead.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export class ToolSearch {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Search for tools or tool sets
   * 
   * @example
   * ```ts
   * const searchToolsOrToolSetsResponse = await client.toolSearch.searchOrSets({ query: 'query_123' });
   * ```
   */
  searchOrSets(params: ToolSearchSearchOrSetsParams, options?: RequestOptions): APIPromise<SearchToolsOrToolSetsResponse> {
    return this._client.requestAPI<SearchToolsOrToolSetsResponse>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/search/tools_or_tool_sets`, query: { query: params.query } };
    }, options);
  }
}
