// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment } from '../core/http.js';
import type { CreateResourceMetadata, Upload, UploadSpec } from '../types.js';

export interface UploadCreateParams {
  metadata: CreateResourceMetadata;
  spec: UploadSpec;
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface UploadRetrieveParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export class Uploads {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Create an upload
   * 
   * @example
   * ```ts
   * const upload = await client.uploads.create({ metadata: { name: 'sample' }, spec: { contentType: 'sample', filename: 'sample', sizeBytes: 'sample' } });
   * ```
   */
  create(params: UploadCreateParams, options?: RequestOptions): APIPromise<Upload> {
    return this._client.requestAPI<Upload>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/uploads`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get an upload by ID
   * 
   * @example
   * ```ts
   * const upload = await client.uploads.retrieve('_123');
   * ```
   */
  retrieve(id: string, params?: UploadRetrieveParams, options?: RequestOptions): APIPromise<Upload> {
    return this._client.requestAPI<Upload>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/uploads/${pathSegment('id', id)}` };
    }, options);
  }
}
