// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateOperationMetadata, CreateWidgetSessionRequest_Secret, DeleteTenantWidgetSessionsResponse, ListWidgetSessionsResponse, WidgetSession, WidgetSessionServiceListWidgetSessionsState, WidgetSessionSpecParam } from '../types.js';
import { wireWidgetSessionSpec } from '../types.js';

export interface WidgetSessionListParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return.
   */
  limit?: number;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string;
  /**
   * Filter to sessions on a specific widget. Accepts the canonical `wgt_…`
   *  form or the `external_id:<value>` form.
   */
  widgetId?: string;
  /**
   * Filter to sessions belonging to a tenant. Accepts the canonical
   *  `tenant_…` form or the `external_id:<value>` form.
   */
  tenantId?: string;
  /**
   * Filter to sessions asserted for a subject. Accepts the canonical
   *  `subj_…` form or the `external_id:<value>` form; the external_id form is
   *  scoped within a tenant and requires `tenant_id` to also be set.
   */
  subjectId?: string;
  /**
   * Filter by state.
   */
  state?: WidgetSessionServiceListWidgetSessionsState;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
  /**
   * Sort order for results (asc or desc by creation time).
   */
  sortOrder?: string;
  /**
   * When true, the `info` field on each returned session is populated.
   *  Requests with this flag count more against your rate limit.
   */
  includeInfo?: boolean;
}

export interface WidgetSessionCreateParams {
  spec: WidgetSessionSpecParam;
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: CreateOperationMetadata;
  /**
   * Secrets to attach to the session.
   */
  secrets?: Array<CreateWidgetSessionRequest_Secret>;
}

export interface WidgetSessionDeleteTenantParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Tenant whose sessions to delete. Required — an empty value is rejected
   *  rather than matching everything. Accepts the canonical `tenant_…` form or
   *  the `external_id:<value>` form.
   */
  tenantId?: string;
}

export interface WidgetSessionRetrieveParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetSessionDeleteParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetSessionRevokeParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export class WidgetSessions {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List widget sessions
   * 
   * @example
   * ```ts
   * const page = await client.widgetSessions.list();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(params?: WidgetSessionListParams, options?: RequestOptions): Promise<Page<WidgetSession>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListWidgetSessionsResponse>({ method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions`, query: { limit: params?.limit, cursor: params?.cursor, widgetId: params?.widgetId, tenantId: params?.tenantId, subjectId: params?.subjectId, state: params?.state, labels: params?.labels, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list({ ..._base, cursor: cursor }, options));
  }

  /**
   * Create a widget session
   * 
   * @example
   * ```ts
   * const widgetSession = await client.widgetSessions.create({ spec: { widgetId: 'sample' } });
   * ```
   */
  create(params: WidgetSessionCreateParams, options?: RequestOptions): APIPromise<WidgetSession> {
    return this._client.requestAPI<WidgetSession>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions`, body: { metadata: params.metadata, spec: wireWidgetSessionSpec(params.spec), secrets: params.secrets } };
    }, options);
  }

  /**
   * Delete all of a tenant's widget sessions
   * 
   * @example
   * ```ts
   * const deleteTenantWidgetSessionsResponse = await client.widgetSessions.deleteTenant();
   * ```
   */
  deleteTenant(params?: WidgetSessionDeleteTenantParams, options?: RequestOptions): APIPromise<DeleteTenantWidgetSessionsResponse> {
    return this._client.requestAPI<DeleteTenantWidgetSessionsResponse>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions`, query: { tenantId: params?.tenantId } };
    }, options);
  }

  /**
   * Get a widget session by ID
   * 
   * @example
   * ```ts
   * const widgetSession = await client.widgetSessions.retrieve('_123');
   * ```
   */
  retrieve(id: string, params?: WidgetSessionRetrieveParams, options?: RequestOptions): APIPromise<WidgetSession> {
    return this._client.requestAPI<WidgetSession>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * Delete a widget session
   * 
   * @example
   * ```ts
   * await client.widgetSessions.delete('_123');
   * ```
   */
  delete(id: string, params?: WidgetSessionDeleteParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions/${pathSegment('id', id)}`, void: true };
    }, options);
  }

  /**
   * Revoke a widget session
   * 
   * @example
   * ```ts
   * const widgetSession = await client.widgetSessions.revoke('_123');
   * ```
   */
  revoke(id: string, params?: WidgetSessionRevokeParams, options?: RequestOptions): APIPromise<WidgetSession> {
    return this._client.requestAPI<WidgetSession>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widget_sessions/${pathSegment('id', id)}:revoke` };
    }, options);
  }
}
