// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateResourceMetadata, ListWidgetsResponse, UpdateResourceMetadata, Widget, WidgetSpec } from '../types.js';

export interface WidgetListParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return.
   */
  limit?: number;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string;
  /**
   * Filter to widgets bound to a specific agent. Accepts the canonical
   *  `agent_…` form or the `external_id:<value>` form.
   */
  agentId?: string;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
  /**
   * Sort order for results (asc or desc by creation time).
   */
  sortOrder?: string;
  /**
   * When true, the `info` field on each returned widget is populated.
   *  Requests with this flag count more against your rate limit.
   */
  includeInfo?: boolean;
}

export interface WidgetCreateParams {
  metadata: CreateResourceMetadata;
  spec: WidgetSpec;
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetRetrieveParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetDeleteParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetUpdateParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: UpdateResourceMetadata;
  spec?: WidgetSpec;
  /**
   * Fields to update.
   */
  updateMask?: string;
}

export interface WidgetArchiveParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WidgetUnarchiveParams {
  /**
   * Workspace ID.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export class Widgets {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List widgets
   * 
   * @example
   * ```ts
   * const page = await client.widgets.list();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(params?: WidgetListParams, options?: RequestOptions): Promise<Page<Widget>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListWidgetsResponse>({ method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets`, query: { limit: params?.limit, cursor: params?.cursor, agentId: params?.agentId, labels: params?.labels, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list({ ..._base, cursor: cursor }, options));
  }

  /**
   * Create a new widget
   * 
   * @example
   * ```ts
   * const widget = await client.widgets.create({ metadata: { name: 'sample' }, spec: { agentId: 'sample' } });
   * ```
   */
  create(params: WidgetCreateParams, options?: RequestOptions): APIPromise<Widget> {
    return this._client.requestAPI<Widget>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get a widget by ID
   * 
   * @example
   * ```ts
   * const widget = await client.widgets.retrieve('_123');
   * ```
   */
  retrieve(id: string, params?: WidgetRetrieveParams, options?: RequestOptions): APIPromise<Widget> {
    return this._client.requestAPI<Widget>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * Delete a widget
   * 
   * @example
   * ```ts
   * await client.widgets.delete('_123');
   * ```
   */
  delete(id: string, params?: WidgetDeleteParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets/${pathSegment('id', id)}`, void: true };
    }, options);
  }

  /**
   * Update a widget
   * 
   * @example
   * ```ts
   * const widget = await client.widgets.update('_123');
   * ```
   */
  update(id: string, params?: WidgetUpdateParams, options?: RequestOptions): APIPromise<Widget> {
    return this._client.requestAPI<Widget>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'PATCH', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets/${pathSegment('id', id)}`, body: { metadata: params?.metadata, spec: params?.spec, updateMask: params?.updateMask } };
    }, options);
  }

  /**
   * Archive a widget
   * 
   * @example
   * ```ts
   * const widget = await client.widgets.archive('_123');
   * ```
   */
  archive(id: string, params?: WidgetArchiveParams, options?: RequestOptions): APIPromise<Widget> {
    return this._client.requestAPI<Widget>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets/${pathSegment('id', id)}:archive` };
    }, options);
  }

  /**
   * Unarchive a widget
   * 
   * @example
   * ```ts
   * const widget = await client.widgets.unarchive('_123');
   * ```
   */
  unarchive(id: string, params?: WidgetUnarchiveParams, options?: RequestOptions): APIPromise<Widget> {
    return this._client.requestAPI<Widget>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/widgets/${pathSegment('id', id)}:unarchive` };
    }, options);
  }
}
