// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateAccountResourceMetadata, ListAccountWorkspacesResponse, ListProfilesResponse, ListWorkspaceMembersResponse, Profile, UpdateAccountResourceMetadata, Workspace, WorkspaceMember, WorkspaceSpec } from '../types.js';

export interface WorkspaceAdminListProfilesParams {
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * Free-form search over profile name and email. Case-insensitive substring
   *  match; empty returns all profiles.
   */
  query?: string;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
}

export interface WorkspaceAdminListAccountParams {
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * When true, archived workspaces are included in the results. Defaults to
   *  false (active workspaces only).
   */
  includeArchived?: boolean;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
}

export interface WorkspaceAdminCreateParams {
  metadata: CreateAccountResourceMetadata;
  spec: WorkspaceSpec;
}

export interface WorkspaceAdminRetrieveParams {
  /**
   * Workspace ID to retrieve (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WorkspaceAdminArchiveParams {
  /**
   * Workspace ID to archive (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WorkspaceAdminUpdateParams {
  /**
   * Workspace ID to update (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: UpdateAccountResourceMetadata;
  spec?: WorkspaceSpec;
  /**
   * Fields to update.
   */
  updateMask?: string;
}

export interface WorkspaceAdminListMembersParams {
  /**
   * The workspace whose members will be listed (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
}

export interface WorkspaceAdminAddMemberParams {
  /**
   * The workspace to add the member to (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * An existing account profile to add. Mutually exclusive with email.
   */
  profileId?: string;
  /**
   * Email address to add (resolve-or-invite). Mutually exclusive with profile_id.
   */
  email?: string;
}

export interface WorkspaceAdminRemoveMemberParams {
  /**
   * The workspace to remove the member from (path).
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export class WorkspaceAdmin {
  constructor(private readonly _client: HttpClient) {}

  /**
   * Search account profiles
   * 
   * @example
   * ```ts
   * const page = await client.workspaceAdmin.listProfiles();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async listProfiles(params?: WorkspaceAdminListProfilesParams, options?: RequestOptions): Promise<Page<Profile>> {
    const _base = snapshotParams(params);
    const response = await this._client.request<ListProfilesResponse>({ method: 'GET', path: `/v1/account/profiles`, query: { limit: params?.limit, cursor: params?.cursor, query: params?.query, labels: params?.labels } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.listProfiles({ ..._base, cursor: cursor }, options));
  }

  /**
   * List all workspaces in the account
   * 
   * @example
   * ```ts
   * const page = await client.workspaceAdmin.listAccount();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async listAccount(params?: WorkspaceAdminListAccountParams, options?: RequestOptions): Promise<Page<Workspace>> {
    const _base = snapshotParams(params);
    const response = await this._client.request<ListAccountWorkspacesResponse>({ method: 'GET', path: `/v1/account/workspaces`, query: { limit: params?.limit, cursor: params?.cursor, includeArchived: params?.includeArchived, labels: params?.labels } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.listAccount({ ..._base, cursor: cursor }, options));
  }

  /**
   * Create a workspace
   * 
   * @example
   * ```ts
   * const workspace = await client.workspaceAdmin.create({ metadata: { name: 'sample' }, spec: {  } });
   * ```
   */
  create(params: WorkspaceAdminCreateParams, options?: RequestOptions): APIPromise<Workspace> {
    return this._client.requestAPI<Workspace>(() => {
      return { method: 'POST', path: `/v1/account/workspaces`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get a workspace by ID
   * 
   * @example
   * ```ts
   * const workspace = await client.workspaceAdmin.retrieve();
   * ```
   */
  retrieve(params?: WorkspaceAdminRetrieveParams, options?: RequestOptions): APIPromise<Workspace> {
    return this._client.requestAPI<Workspace>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}` };
    }, options);
  }

  /**
   * Archive a workspace
   * 
   * @example
   * ```ts
   * await client.workspaceAdmin.archive();
   * ```
   */
  archive(params?: WorkspaceAdminArchiveParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}`, void: true };
    }, options);
  }

  /**
   * Update a workspace
   * 
   * @example
   * ```ts
   * const workspace = await client.workspaceAdmin.update();
   * ```
   */
  update(params?: WorkspaceAdminUpdateParams, options?: RequestOptions): APIPromise<Workspace> {
    return this._client.requestAPI<Workspace>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'PATCH', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}`, body: { metadata: params?.metadata, spec: params?.spec, updateMask: params?.updateMask } };
    }, options);
  }

  /**
   * List workspace members
   * 
   * @example
   * ```ts
   * const page = await client.workspaceAdmin.listMembers();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async listMembers(params?: WorkspaceAdminListMembersParams, options?: RequestOptions): Promise<Page<WorkspaceMember>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListWorkspaceMembersResponse>({ method: 'GET', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}/members`, query: { limit: params?.limit, cursor: params?.cursor } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.listMembers({ ..._base, cursor: cursor }, options));
  }

  /**
   * Add a member to a workspace
   * 
   * @example
   * ```ts
   * const workspaceMember = await client.workspaceAdmin.addMember();
   * ```
   */
  addMember(params?: WorkspaceAdminAddMemberParams, options?: RequestOptions): APIPromise<WorkspaceMember> {
    return this._client.requestAPI<WorkspaceMember>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}/members`, body: { profileId: params?.profileId, email: params?.email } };
    }, options);
  }

  /**
   * Remove a member from a workspace
   * 
   * @example
   * ```ts
   * await client.workspaceAdmin.removeMember('profile_123');
   * ```
   */
  removeMember(profileId: string, params?: WorkspaceAdminRemoveMemberParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/account/workspaces/${pathSegment('workspaceId', workspaceId)}/members/${pathSegment('profileId', profileId)}`, void: true };
    }, options);
  }
}
