// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, APIPromise, pathSegment, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { CreateResourceMetadata, ListWorkspaceSecretsResponse, UpdateResourceMetadata, WorkspaceSecret, WorkspaceSecretSpec } from '../types.js';

export interface WorkspaceSecretListParams {
  /**
   * The workspace whose secrets will be listed.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * Filter expression (query param: prefix)
   */
  prefix?: string;
  /**
   * Free-form search query
   */
  query?: string;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
  /**
   * Sort order for results (asc or desc by creation time)
   */
  sortOrder?: string;
  /**
   * When set to true you may use more of your alloted API rate-limit
   */
  includeInfo?: boolean;
}

export interface WorkspaceSecretCreateParams {
  metadata: CreateResourceMetadata;
  spec: WorkspaceSecretSpec;
  /**
   * The workspace that will own this secret.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WorkspaceSecretRetrieveParams {
  /**
   * The workspace the secret belongs to.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WorkspaceSecretDeleteParams {
  /**
   * The workspace the secret belongs to.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
}

export interface WorkspaceSecretUpdateParams {
  /**
   * The workspace the secret belongs to.
   * 
   * Defaults to the client-level `workspaceId` option or the CADENYA_WORKSPACE_ID environment variable.
   */
  workspaceId?: string;
  metadata?: UpdateResourceMetadata;
  spec?: WorkspaceSecretSpec;
  /**
   * Fields to update.
   */
  updateMask?: string;
}

export class WorkspaceSecrets {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List workspace secrets
   * 
   * @example
   * ```ts
   * const page = await client.workspaceSecrets.list();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(params?: WorkspaceSecretListParams, options?: RequestOptions): Promise<Page<WorkspaceSecret>> {
    const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
    if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
    const _base = snapshotParams(params);
    const response = await this._client.request<ListWorkspaceSecretsResponse>({ method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/workspace_secrets`, query: { limit: params?.limit, cursor: params?.cursor, prefix: params?.prefix, query: params?.query, labels: params?.labels, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list({ ..._base, cursor: cursor }, options));
  }

  /**
   * Create a new workspace secret
   * 
   * @example
   * ```ts
   * const workspaceSecret = await client.workspaceSecrets.create({ metadata: { name: 'sample' }, spec: {  } });
   * ```
   */
  create(params: WorkspaceSecretCreateParams, options?: RequestOptions): APIPromise<WorkspaceSecret> {
    return this._client.requestAPI<WorkspaceSecret>(() => {
      const workspaceId = String(params.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'POST', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/workspace_secrets`, body: { metadata: params.metadata, spec: params.spec } };
    }, options);
  }

  /**
   * Get a workspace secret by ID
   * 
   * @example
   * ```ts
   * const workspaceSecret = await client.workspaceSecrets.retrieve('_123');
   * ```
   */
  retrieve(id: string, params?: WorkspaceSecretRetrieveParams, options?: RequestOptions): APIPromise<WorkspaceSecret> {
    return this._client.requestAPI<WorkspaceSecret>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'GET', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/workspace_secrets/${pathSegment('id', id)}` };
    }, options);
  }

  /**
   * Delete a workspace secret
   * 
   * @example
   * ```ts
   * await client.workspaceSecrets.delete('_123');
   * ```
   */
  delete(id: string, params?: WorkspaceSecretDeleteParams, options?: RequestOptions): APIPromise<void> {
    return this._client.requestAPI<void>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'DELETE', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/workspace_secrets/${pathSegment('id', id)}`, void: true };
    }, options);
  }

  /**
   * Update a workspace secret
   * 
   * @example
   * ```ts
   * const workspaceSecret = await client.workspaceSecrets.update('_123');
   * ```
   */
  update(id: string, params?: WorkspaceSecretUpdateParams, options?: RequestOptions): APIPromise<WorkspaceSecret> {
    return this._client.requestAPI<WorkspaceSecret>(() => {
      const workspaceId = String(params?.workspaceId ?? this._client.defaults['workspaceId'] ?? '').trim() || undefined;
      if (workspaceId === undefined) throw new Error("Missing 'workspaceId': pass it in params, set it on the client, or set the CADENYA_WORKSPACE_ID environment variable.");
      return { method: 'PATCH', path: `/v1/workspaces/${pathSegment('workspaceId', workspaceId)}/workspace_secrets/${pathSegment('id', id)}`, body: { metadata: params?.metadata, spec: params?.spec, updateMask: params?.updateMask } };
    }, options);
  }
}
