// Generated by redwood. Do not edit by hand.

import { HttpClient, RequestOptions, snapshotParams } from '../core/http.js';
import { Page } from '../core/pagination.js';
import type { ListWorkspacesResponse, Workspace } from '../types.js';

export interface WorkspaceListParams {
  /**
   * Maximum number of results to return
   */
  limit?: number;
  /**
   * Pagination cursor from previous response
   */
  cursor?: string;
  /**
   * Sort order for results (asc or desc by creation time)
   */
  sortOrder?: string;
  /**
   * When set to true you may use more of your alloted API rate-limit
   */
  includeInfo?: boolean;
  /**
   * Filters by metadata labels. Comma-separated key=value pairs,
   *  e.g. "env=prod,team=ai". A resource matches only if every pair
   *  matches exactly (AND semantics).
   */
  labels?: string;
}

export class Workspaces {
  constructor(private readonly _client: HttpClient) {}

  /**
   * List workspaces
   * 
   * @example
   * ```ts
   * const page = await client.workspaces.list();
   * for await (const item of page) {
   *   // auto-fetches every page
   * }
   * ```
   */
  async list(params?: WorkspaceListParams, options?: RequestOptions): Promise<Page<Workspace>> {
    const _base = snapshotParams(params);
    const response = await this._client.request<ListWorkspacesResponse>({ method: 'GET', path: `/v1/workspaces`, query: { limit: params?.limit, cursor: params?.cursor, sortOrder: params?.sortOrder, includeInfo: params?.includeInfo, labels: params?.labels } }, options);
    return new Page(response.items ?? [], response.pagination?.nextCursor, (cursor) => this.list({ ..._base, cursor: cursor }, options));
  }
}
