// Generated by redwood. Do not edit by hand.

import { HttpClient } from './core/http.js';
import type { Logger, LogLevel } from './core/http.js';
import { Webhooks } from './webhooks.js';
import { Accounts } from './resources/accounts.js';
import { ApiKeys } from './resources/api-keys.js';
import { WorkspaceAdmin } from './resources/workspace-admin.js';
import { Profiles } from './resources/profiles.js';
import { Workspaces } from './resources/workspaces.js';
import { Agents } from './resources/agents.js';
import { AiProviderKeys } from './resources/ai-provider-keys.js';
import { MemoryLayers } from './resources/memory-layers.js';
import { Models } from './resources/models.js';
import { Objectives } from './resources/objectives.js';
import { ToolSearch } from './resources/tool-search.js';
import { Tenants } from './resources/tenants.js';
import { ToolSets } from './resources/tool-sets.js';
import { Uploads } from './resources/uploads.js';
import { WidgetSessions } from './resources/widget-sessions.js';
import { Widgets } from './resources/widgets.js';
import { WorkspaceSecrets } from './resources/workspace-secrets.js';

export interface ClientOptions {
  /** API key. Defaults to the CADENYA_API_KEY environment variable. */
  apiKey?: string;
  /** Override the API base URL. Defaults to https://api.cadenya.com. */
  baseURL?: string;
  /** Max automatic retries for retryable failures. Defaults to 0. */
  maxRetries?: number;
  /**
   * Deadline for ordinary (non-streaming) requests in milliseconds; override
   * per request with `options.timeout`. Streams bound only response-header
   * acquisition — body lifetime stays under the caller's AbortSignal.
   * Defaults to 60000; a non-finite or <= 0 value disables the deadline.
   */
  timeout?: number;
  /** Headers sent with every request. */
  defaultHeaders?: Record<string, string>;
  /** Custom fetch implementation. */
  fetch?: typeof fetch;
  /** Destination for SDK logs. Defaults to `console`. */
  logger?: Logger;
  /** 'debug' | 'warn' (default) | 'off'. Never logs headers or bodies. */
  logLevel?: LogLevel;
  /** Default `workspaceId` for every call that takes one. Defaults to the CADENYA_WORKSPACE_ID environment variable. */
  workspaceId?: string;
  /** Secret for webhook signature verification. Defaults to the CADENYA_WEBHOOK_SECRET environment variable. */
  webhookSecret?: string;
}

export class Cadenya {
  readonly accounts: Accounts;
  readonly apiKeys: ApiKeys;
  readonly workspaceAdmin: WorkspaceAdmin;
  readonly profiles: Profiles;
  readonly workspaces: Workspaces;
  readonly agents: Agents;
  readonly aiProviderKeys: AiProviderKeys;
  readonly memoryLayers: MemoryLayers;
  readonly models: Models;
  readonly objectives: Objectives;
  readonly toolSearch: ToolSearch;
  readonly tenants: Tenants;
  readonly toolSets: ToolSets;
  readonly uploads: Uploads;
  readonly widgetSessions: WidgetSessions;
  readonly widgets: Widgets;
  readonly workspaceSecrets: WorkspaceSecrets;
  readonly webhooks: Webhooks;

  private readonly _client: HttpClient;

  constructor(options: ClientOptions = {}) {
    // Presence is not validity: empty strings from options or environment
    // are configuration mistakes, not credentials.
    const apiKey = resolveOption('apiKey', options.apiKey, readEnv('CADENYA_API_KEY'));
    if (!apiKey) {
      throw new Error(
        "Missing API key. Pass it with `new Cadenya({ apiKey })` or set the CADENYA_API_KEY environment variable.",
      );
    }
    this._client = new HttpClient({
      baseURL: resolveOption('baseURL', options.baseURL, readEnv('CADENYA_BASE_URL')) ?? 'https://api.cadenya.com',
      authHeader: () => ({ Authorization: `Bearer ${apiKey}` }),
      maxRetries: options.maxRetries ?? 0,
      timeout: options.timeout,
      defaultHeaders: { 'User-Agent': 'cadenya-typescript/1.0.1 (api 1.0)', ...options.defaultHeaders },
      fetch: options.fetch,
      logger: options.logger,
      logLevel: options.logLevel,
      defaults: { workspaceId: resolveOption('workspaceId', options.workspaceId, readEnv('CADENYA_WORKSPACE_ID')) },
    });
    this.webhooks = new Webhooks(resolveOption('webhookSecret', options.webhookSecret, readEnv('CADENYA_WEBHOOK_SECRET')));
    this.accounts = new Accounts(this._client);
    this.apiKeys = new ApiKeys(this._client);
    this.workspaceAdmin = new WorkspaceAdmin(this._client);
    this.profiles = new Profiles(this._client);
    this.workspaces = new Workspaces(this._client);
    this.agents = new Agents(this._client);
    this.aiProviderKeys = new AiProviderKeys(this._client);
    this.memoryLayers = new MemoryLayers(this._client);
    this.models = new Models(this._client);
    this.objectives = new Objectives(this._client);
    this.toolSearch = new ToolSearch(this._client);
    this.tenants = new Tenants(this._client);
    this.toolSets = new ToolSets(this._client);
    this.uploads = new Uploads(this._client);
    this.widgetSessions = new WidgetSessions(this._client);
    this.widgets = new Widgets(this._client);
    this.workspaceSecrets = new WorkspaceSecrets(this._client);
  }
}

function readEnv(name: string): string | undefined {
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env;
  return env?.[name];
}

// Presence is not validity: an explicitly provided option must be usable —
// a blank value is a configuration mistake and never silently falls back to
// the environment or a default. Only an OMITTED option reads the env.
function resolveOption(
  label: string,
  explicit: string | undefined,
  env: string | undefined,
): string | undefined {
  if (explicit !== undefined) {
    const value = explicit.trim();
    if (!value) {
      throw new Error(
        `${label} must not be blank when provided explicitly; omit it to use the environment instead.`,
      );
    }
    return value;
  }
  return env?.trim() || undefined;
}
