name: CI
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  typecheck:
    timeout-minutes: 10
    name: typecheck
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run typecheck

  build:
    timeout-minutes: 5
    name: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Check build
        run: npm run build
